### PR TITLE
Fix codegen for continuation tokens

### LINKED ISSUE #1494: http-client-go Paging ContinuationToken Implementation

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Propagate the response token to the next request.
Preserve any set query parameters for reinjection.
Added discrete modeling for pagination strategies to the code model.

Fixes https://github.com/Azure/autorest.go/issues/1494

### CODE REVIEW

File: packages/codegen.go/src/core/operations.ts [hunk 1]
```diff
@@ -580,97 +580,193 @@ function getZeroReturnValue(method: go.MethodType, apiType: 'lro' | 'op' | 'hand
...
-        const paramName = nextOpParams[i].trim().split(' ')[0];
-        const paramType = nextOpParams[i].trim().split(' ')[1];
-        if (paramName.startsWith('next') && paramType === 'string') {
-          nextOpParams[i] = 'encodedNextLink';
+
+  /** emits code to check the HTTP status code and conditionally call the response handler */
+  const emitStatusCodeCheckAndResponse = function (respVarName: string, indent: helpers.Indentation): string {
+    let content = `${indent.get()}${helpers.buildIfBlock(indent, {
+      condition: `!runtime.HasStatusCode(${respVarName}, http.StatusOK)`,
+      body: (indent) => `${indent.get()}return ${getZeroReturnValue(method, 'op')}, runtime.NewResponseError(${respVarName})\n`,
```
[the remark this answers is not in the document]
Comment (jhendrixMSFT) [reply packages/codegen.go/src/core/operations.ts:669]: This is incorrect.

File: packages/codegen.go/src/core/operations.ts [hunk 2]
```diff
@@ -580,97 +580,193 @@ function getZeroReturnValue(method: go.MethodType, apiType: 'lro' | 'op' | 'hand
...
+        }
+
+        text += `${indent.get()}${helpers.buildIfBlock(indent, {
+          condition: `page != nil${nestedNilChecks}`,
+          body: (indent) => `${indent.get()}${optionsParamName}.${ms.requestToken.name} = page.${respToken}\n`,
+        })}\n`;
+
+        text += callCreateRequestWithErrCheck(method, 'req', indent);
+        text += callPipelineDoWithErrCheck(method, 'req', 'resp', indent);
+        text += emitStatusCodeCheckAndResponse('resp', indent);
```
[the remark this answers is not in the document]
Comment (jhendrixMSFT) [reply packages/codegen.go/src/core/operations.ts:709]: This is incorrect.

File: packages/typespec-go/src/tcgcadapter/clients.ts [hunk 3]
```diff
@@ -556,10 +547,94 @@ export class ClientAdapter {
...
+      const tokenReq = sdkMethod.pagingMetadata.continuationTokenParameterSegments[0];
+      const tokenResp = sdkMethod.pagingMetadata.continuationTokenResponseSegments[0];
+
+      // find the continuation token parameter
+      let requestToken: go.HeaderScalarParameter | go.QueryScalarParameter;
+      switch (tokenReq.kind) {
+        case 'method': {
+          const tokenParam = paramsMap.get(tokenReq);
+          if (!tokenParam) {
+            throw new AdapterError('InternalError', `missing continuation token request parameter name ${tokenResp.name} for operation ${sdkMethod.name}`, sdkMethod.__raw?.node);
```
[the remark this answers is not in the document]
Comment (jhendrixMSFT) [reply packages/typespec-go/src/tcgcadapter/clients.ts]: fixed

**Comment by jhendrixMSFT** [comment]
This is largely based on how it's implemented in the Rust emitter.

File: packages/typespec-go/src/tcgcadapter/clients.ts [hunk 4]
```diff
@@ -556,10 +547,94 @@ export class ClientAdapter {
...
+          // the most likely explanation for this is lack of reference equality
+          throw new AdapterError('InternalError', `missing next link field name ${segment.name} for operation ${sdkMethod.name}`, sdkMethod.__raw?.node);
+        }
+        nextLinkPath.push(nextLinkField);
+      }
+      return nextLinkPath;
+    };
+
+    if (sdkMethod.pagingMetadata.nextLinkOperation) {
+      throw new AdapterError('UnsupportedTsp', 'next page operation NYI', sdkMethod.__raw?.node);
```
Comment (RickWinter) [inline packages/typespec-go/src/tcgcadapter/clients.ts:587]: This should get a test for a service that defines an explicit next-page operation.

File: packages/codemodel.go/src/client.ts [hunk 5]
```diff
@@ -239,6 +239,41 @@ export interface PageableMethod extends PageableMethodBase {
...
+
+  /**
+   * the field path in the response that contains the next link URL.
+   * one entry at minimum. when the next link is nested in the response
+   * type, the array will contain the "path" to the next link.
+   */
+  nextLinkPath: Array<type.ModelField>;
+
+  /** the query params to be reinjected when fetching pages. can be empty */
+  reinjectedParams: Array<param.QueryCollectionParameter | param.QueryScalarParameter>;
```
Comment (RickWinter) [inline packages/codemodel.go/src/client.ts]: This value gets set but nothing ever uses it. Also in tcgcadapter/clinets.ts you throw that paging with re-injected parameters is not supported.

did you intend for this to be a TODO?

File: packages/codegen.go/src/core/operations.ts [hunk 6]
```diff
@@ -580,97 +580,193 @@ function getZeroReturnValue(method: go.MethodType, apiType: 'lro' | 'op' | 'hand
...
+
+  if (method.strategy) {
+    switch (method.strategy.kind) {
+      case 'continuationToken': {
+        const ms = method.strategy;
+        const optionsParamName = method.optionalParamsGroup.name;
+        text += `${indent.get()}${helpers.buildIfBlock(indent, {
+          condition: `${optionsParamName} == nil`,
+          body: (indent) => `${indent.get()}${optionsParamName} = &${method.optionalParamsGroup.groupName}{}\n`,
+        })}\n`;
```
Comment (RickWinter) [inline packages/codegen.go/src/core/operations.ts:684]: In the generated code a non-nil options will have options.Token overwritten on subsequent pages which means we are mutating the input. Should options be cloned locally?

File: packages/typespec-go/src/tcgcadapter/types.ts [hunk 7]
```diff
@@ -656,6 +660,11 @@ export class TypeAdapter {
       xml: prop.serializationOptions.xml,
     });
 
+    // it's possible for different models to reference the same property definition
+    if (!this.fieldsMap.get(prop)) {
```
Comment (RickWinter) [inline packages/typespec-go/src/tcgcadapter/types.ts]:
```suggestion
    if (!this.fieldsMap.has(prop)) {
```

File: packages/typespec-go/src/tcgcadapter/types.ts [hunk 8]
```diff
@@ -19,6 +19,9 @@ export class TypeAdapter {
   /** the code model for this adapter */
   readonly codeModel: go.CodeModel;
 
+  // maps a tcgc model field to the adapted struct field
+  readonly fieldsMap: Map<tcgc.SdkModelPropertyType | tcgc.SdkPathParameter, go.ModelField>;
```
Comment (RickWinter) [inline packages/typespec-go/src/tcgcadapter/types.ts]: Is the Map for future use? Right now you only ever use the SdkModelPropertyType.

File: packages/autorest.go/src/m4togocodemodel/clients.ts [hunk 9]
```diff
@@ -120,6 +101,20 @@ function adaptNextPageMethod(op: m4.Operation, m4CodeModel: m4.CodeModel, client
 }
 
 function populateMethod(op: m4.Operation, m4CodeModel: m4.CodeModel, method: go.MethodType | go.NextPageMethod): void {
+  const getNextLinkStrategy = function (method: go.LROPageableMethod | go.PageableMethod, nextLinkName: string): go.PageableStrategyNextLink {
```
Comment (RickWinter) [inline packages/autorest.go/src/m4togocodemodel/clients.ts:104]: Nit: Should this method be in module scope rather than function?

File: packages/typespec-go/src/tcgcadapter/clients.ts (hunk 4 above)
Comment (jhendrixMSFT) [reply packages/typespec-go/src/tcgcadapter/clients.ts:587]: I opened https://github.com/Azure/autorest.go/issues/1929 to track this (I thought we already had an issue for this).

File: packages/codemodel.go/src/client.ts (hunk 5 above)
Comment (jhendrixMSFT) [reply packages/codemodel.go/src/client.ts]: Good catch.  This is copy/pasta from the Rust implementation, and we handle reinjected params differently in Go so it's not needed.

File: packages/typespec-go/src/tcgcadapter/types.ts (hunk 8 above)
Comment (jhendrixMSFT) [reply packages/typespec-go/src/tcgcadapter/types.ts]: This is used in `clients.ts` function `adaptPagingStrategy()`.  You are correct though that it doesn't need to support `tcgc.SdkPathParameter`.

File: packages/autorest.go/src/m4togocodemodel/clients.ts (hunk 9 above)
Comment (jhendrixMSFT) [reply packages/autorest.go/src/m4togocodemodel/clients.ts:104]: No as it's only used in `populateMethod()`.

File: packages/codegen.go/src/core/operations.ts (hunk 6 above)
Comment (jhendrixMSFT) [reply packages/codegen.go/src/core/operations.ts:684]: The overwriting is expected and will only happen on subsequent pages, never the first (we explicitly test this).

I'm unsure how I feel about mutating the input though (thinking....).

File: packages/codemodel.go/src/client.ts (hunk 5 above)
Comment (jhendrixMSFT) [reply packages/codemodel.go/src/client.ts]: fixed

File: packages/typespec-go/src/tcgcadapter/types.ts (hunk 7 above)
Comment (jhendrixMSFT) [reply packages/typespec-go/src/tcgcadapter/types.ts]: fixed

File: packages/typespec-go/src/tcgcadapter/types.ts (hunk 8 above)
Comment (jhendrixMSFT) [reply packages/typespec-go/src/tcgcadapter/types.ts]: fixed

File: packages/codegen.go/src/core/operations.ts (hunk 6 above)
Comment (jhendrixMSFT) [reply packages/codegen.go/src/core/operations.ts:684]: This needs to be fixed.

Comment (jhendrixMSFT) [reply packages/codegen.go/src/core/operations.ts:684]: fixed

**Review by RickWinter — APPROVED** [review]
